# App
spring.application.name=etf-advisor
server.port=8080


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/etfadvisor
spring.datasource.username=sa
spring.datasource.password=secret


# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JSON schön formatiert
spring.jackson.serialization.indent-output=true

# Alpaca API--> muss noch in ne env
alpaca.api.key=DEIN_KEY_HIER
alpaca.api.secret=DEIN_SECRET_HIER
alpaca.api.baseUrl=https://data.alpaca.markets/v2

