# App
spring.application.name=etf-advisor
server.port=8080


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/etfadvisor
spring.datasource.username=sa
spring.datasource.password=secret


# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JSON schön formatiert
spring.jackson.serialization.indent-output=true

# Alpaca API (key + secret kommen aus Key/MyKeys.env via @PropertySource)
alpaca.api.base-url=https://data.alpaca.markets/v2
alpaca.api.connect-timeout-ms=2000
alpaca.api.read-timeout-ms=5000

# Ninja API
ninjas.api.key=${NINJAS_API_KEY:demo}
ninjas.api.base-url=https://api.api-ninjas.com
ninjas.api.connect-timeout-ms=2000
ninjas.api.read-timeout-ms=5000
# JWT
jwt.secret=${JWT_SECRET:mein-super-geheimer-schluessel-der-mindestens-32-zeichen-lang-ist}
jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
